resilience4j:
  retry:
    instances:
      paymentService:
        maxAttempts: 3
        waitDuration: 3s
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - vn.payos.exception.PayOSException
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      paymentService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  ratelimiter:
    instances:
      paymentServiceRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1m
        timeoutDuration: 500ms
  logging:
    level:
      io.github.resilience4j: DEBUG
