resilience4j.timelimiter:
  instances:
    userProfileTimelimiter:
      timeoutDuration: 2s
      cancelRunningFuture: true

resilience4j.retry:
  instances:
    userProfileRetry:
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.lang.reflect.UndeclaredThrowableException
    sendOtpRetry:
      maxAttempts: 3
      waitDuration: 3s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - feign.FeignException
        - feign.RetryableException